---
title: "Assignment_2"
author: "Clayton Glenn"
date: "March 1, 2018"
output:
  word_document:
    toc: yes
  pdf_document: default
  html_document:
    fig_caption: yes
    fig_height: 4
    fig_width: 5
    number_sections: no
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

17/17 questions complete

#1. [3 marks] MS 3.36 - pg 105-106

###A

\[\quad P(Match\cap Experts)=92.12\%\]

###B

\[P(Match\cap Novice)=74.55\%\]

###C

Novice are more likely to fail the fingerprint match test with a lesser probability that the Novice will be right.


#2. [3 marks] MS 3.52 - pg 111

###A

\[P(U|+)=50\%\]

###B

\[P(N|-)=99\%\]

###C

\[P(+|U)=P(U\cap +)P(U)\]
\[=\frac{0.059\cdot 0.50}1=29.5\%\]


#3. [1 marks] MS Theorem 3.1 - pg 113 Prove the theorem in your own words.

##Multiplicative Rule

\[n_1n_2n_3n_4\cdot \cdot \cdot \cdot n_k\]
This can be explained by simply having an x amount of sequences of y amount of numbers. 

#4. [1 marks] MS Theorem 3.2 - pg 114 Prove the theorem in your own words.

##Permutations Rule

\[P^{N}_{n}=N(N-1)(N-2)\cdot \cdot \cdot \cdot (N-n-1)=\frac{N!}{(N-n)!}\]
This can be proved through the multiplication rule. After one element from a set of K elements has been placed in a position, the element is removed and the set of elements to be chosen from is K-1. After the next is pulled, then the set consists of K-2 elements and so on, until the nth position is filled which is written as (K-n-1) where n is the factorial. Applying the Multiplicative Rule will result in the above equation.

#5. [1 marks] MS Theorem 3.3 - pg 116 Prove the theorem in your own words.

##Partitions Rule

\[\frac{N!}{n_1!n_2!\cdot \cdot \cdot n_k!}\quad \text{where }n_1+n_2+\cdot \cdot \cdot+n_k=N\]
This is just a variation of the Permutations Rule where there are N elements partitioned into multiple sets. The sets together still contain N amount of elements cumulatively. Through the Multiplicative Rule, you can find the above equation by multiplying the Permutation of N elements by the factorial of cardinality of each set of numbers that you are trying to partition.

#6. [1 marks] MS Theorem 3.4 - pg 117 Prove the theorem in your own words.

###Combinations Rule

\[\binom{N}{n}=\frac{N!}{n!(N-n)!}\]
This rule is a variation of the Partitions Rule, where the result is just the number of ways you can take n elements from a Set of N elements. The "two" sets of numbers n + N-n = N so this still follows the Partition's Rule.

#7. [3 marks] MS 4.2 - pg 138

###A

\[.09+.3+.37+.2+.04=1\]

###B

\[P(3\leq X\leq 4)=P(3)+P(4)=24\%\]

###C

\[P(X\leq 2)=P(0)+P(1)=39\%\]


#8. [4 marks] MS 4.12 - pg 143

###A

\[P(0\leq X\leq 20)=1\]

###B

\[P(10\leq Y)=P(10)+P(11)+...+P(20)=14\%\]

###C

\[\mu=\sum_{y=0}^{n}yP(y)=0(0.17)+1(0.1)+...+20(0.005)=4.655\]

\[\sigma^2=\sum_{y=0}^{n}(y - \mu)^2 P(y)=(0 - 
4.655)2(.17)+...+(20-4.655)2(0.005)=19.856\]

###D

\[P(0 \leq Y \leq 6)\]



#9. [4 marks] MS 4.34 - pg 154

###A

\[P(y)=\binom{n}{y}p^yq^{n-y} = \frac{n!}{y!(n-y)!}p^yq^{n-y}\]
\[=\frac{25!}{10!15!}0.70^{10}0.31^{5}=0.13249\%\]

###B

\[P(Y \leq 5)=\sum_{y=0}^{n}\binom{n}{y}p^yq^{n-y}=0.0027726\%\]

###C

\[Mean=\mu=np=17.5\]

\[Variance=\sigma^2=npq=5.25\]

###D

Most of the probability lies within 2 standard deviations of 17.5, which is

\[12.9174\leq Y\leq 22.0826\]


#10. [2 marks] MS 4.46 - pg 158

###A

\[P(5:5)=\frac{50!}{5!^{10}}\cdot .1^{50}=0.00004912\%\]

###B

\[P(1,Yn)=\frac{50!}{1!49!}(.1)^{49+1}=5X10^{-49}\]


#11. [2 marks] MS 4.54 - pg 162

###A

\[P(Y)=(1-p)^{y-1}p\]

###B

\[E(y)=1/p=1/.4=2.5\]

###C

\[P(1)=(1-0.4)^0.4=0.4\]

###D

\[P(Y>2)=1-P(Y \leq2)=1-P(1)-P(2)\]

\[P(Y>2)=1-.4-.6*.4=0.36\]

#12. [2 marks] MS 4.66 - pg 168

###A

\[r=8 \quad n=10 \quad N=209\]

\[E(y)=\frac{rn}{N}=.38278\]

###B

This means the mean is less than 1 facility treats hazardous waste on site, and the average is closer to zero for a sample of 10 factories.

###C

\[P(y)=\frac{E(y)n}{N}\]
\[=\frac{.38278\cdot 4}{10}=0.15311\]


#13. [3 marks] MS 4.78 - pg 173

###A

\[Var(y)=\lambda=0.03\]

###B

Y=1, the probability is 2.911% and at Y=2, the probability drops exponentially. This shows, the distribution is very steep and is greater than 0.

###C

\[P(y)=\frac{\lambda^ye^{-\lambda}}{y!}\]

\[P(0)=\frac{.03^0e^{-.03}}{0!}=e^{-.03}=97.045\%\]


#14. [4 marks] MS 5.2 - pg 191

###A

\[\int_{x}f(x)dx=1\]

\[\int_{1}^{0}c(2-y)dy=1\Rightarrow c[2y-y^2)^2|^{1}_{0}=1\]

\[=c(3/2)=1\Rightarrow c=2/3\]

###B

\[F(x)= 2/3(2y-\frac{y^2}{2})\ \ \ \ 0\leq Y \leq 1\]

###C

\[F(0.4)=2/3(.8-.08)=0.48\]

###D

\[P(.1\leq Y\leq .6)=2/3(1.2-.18)-2/3(.2-0.05)=.58\]





#15. [3 marks] MS 5.10 - pg 196

###A

\[Mean=E(y)=\int^{\infty}_{-\infty}yf(y)dy\]
\[=\int^{5}_{-5}\frac{3}{500}(25y-y^3)dy\]
\[=3500[252(y2|^5_{-5})-14(y4|^5_{-5})]\]
\[=\frac{3}{500} \left [  \frac{25}{2} (0)-\frac{1}{4} (0)\right]\]
\[0\quad minutes\]

\[Variance=E(y^2)-(E(y))^2\text{ where E(y)=0} \Rightarrow E(y^2)\]
\[Variance=\frac{3}{500}\int^{5}_{-5}(25y^2-y^4)dy\]
\[=\frac{3}{500}[25/3(y^3|^{5}_{-5}) - 1/5(y^5|^5_{-5}]\]
\[=75/1500(5^3+5^3)-2/2500(5^5+5^5)\]
\[=50/10=5 minutes\]

###B

\[-1/12 < Y < 1/12\]

The mean does not change and stays Zero because the limits are 
circular.

The variance does not change, but is converted to hours, which is 1/12 
hours.

###C

\[-300 < Y < 300\]

The mean does not change and stays Zero because the limits are 
circular.

The variance does not change, but is converted to seconds, which is 
300 seconds.





#16. [3 marks] MS 5.36 - pg 205

###A

\[\mu=\text{50 milligrams} \quad \sigma=\text{3.2 milligrams}\]

\[P(X>45)\]

\[P(z>\frac{45-50}{3.2})=1-P(z \leq \frac{45-50}{3.2})\]

\[=1-P(z \leq -1.56)\Rightarrow 1-0.0594=94.06\%\]

###B

\[P(X<55)\]

\[P(z < \frac{55-50}{3.2})=z<1.56=94.06\%\]

###C

\[P(51<X<52)=P(x<52)-P(x<51)\]
\[=P(z < \frac{52-50}{3.2})-P(z < \frac{51-50}{3.2})\]
\[=(z<.63)-(z<.31)\]
\[=.7357-.6217=11.4\%\]



#17. [5 marks] MS 5.38- pg 205

###A

\[z=\frac{x-\mu}{\sigma}\]

\[z(500)=\frac{500-605}{185}=-.57 \quad \quad z(700)=\frac{700-605}{185}=.51\]

\[P(-.57<Z<.51)=.695-.2843=41.07\%\]

###B

\[z=\frac{x-\mu}{\sigma}\]

\[
z(400)  =\frac{400-605}{185}=-1.11
\quad z(500) =\frac{500-605}{185} =-.57
\]

\[P(-1.11<Z<-.57)  =.2843-.1335 =15.08\%\]

###C

\[z  =\frac{x-\mu}{\sigma} = \frac{850-605}{185}=1.32\]

\[P(z<1.32)=90.66\%\]

###D
\[z  =\frac{x-\mu}{\sigma} =\frac{1000-605}{185}=2.14\]

\[P(z<2.14)=1.62\%\]

###E

\[P(X>x_0)=0.1 \Rightarrow P(X<x_0)=0.9\]
\[P(\frac{X-\mu}{\sigma}<\frac{x_0-\mu}{\sigma})=0.9\]
\[P(Z<\frac{x_0-\mu}{\sigma})=0.9\]
\[x_0=605+185 \cdot 1.282=842.17\]


